name: Select a Trope then post

on:
  workflow_dispatch:
# schedule:
 # - cron: '15 * * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Python with pip cache
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Toot the trope
      env:
        TOOT_CONFIG: ${{ secrets.TOOT_CONFIG }}
      run: |-
        mkdir -p ~/.config/toot
        echo $TOOT_CONFIG > ~/.config/toot/config.json

    - name: Select & Print Random Trope
      run: |
      import random
      def print_random_line(file_path):
          with open(file_path, 'r') as file:
              lines = file.readlines()  # Read all lines into a list
          random_line = random.choice(lines).strip()  # Randomly select a line and strip newline
          print(random_line)
